### ISSUE TITLE
Branch: Restify - cf35cc5835268d96024f6ebbc7808bbfd202452b

### ISSUE THREAD

**Issue by mezerotm** [mezerotm/eco#1]
Some changes made to the database have minor issues.
- Several stored procedures do no have [END IF](https://dev.mysql.com/doc/refman/5.7/en/if.html)
- dummy_data does not reflect new changes [tables.sql](https://github.com/mezerotm/eco/blob/cf35cc5835268d96024f6ebbc7808bbfd202452b/src/database/tables.sql#L18)
- some [IF STATEMENTS](https://github.com/mezerotm/eco/blob/cf35cc5835268d96024f6ebbc7808bbfd202452b/src/database/procedures/devices_stored_procedures.sql#L70) no not have ending parathesis and are missing __THEN__ keywords

These are not cherry picked instances, this is reflected throughout most procedures.

One final suggestion I would appreciate, if within the  [setup_database.sql](https://github.com/mezerotm/eco/blob/restify/src/database/setup_database.sql) it would drop the tables before it created them.

**Comment by NJTuley** [comment]
Sorry about that those were oversights on my part and I will make the changes

**Comment by mezerotm** [comment]
ced740162152cdadf18a8e5d565cec115006201f
